# Generated by Django 5.2.1 on 2025-08-07 13:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                50, "Description must be at least 50 symbols"
                            ),
                            django.core.validators.MaxLengthValidator(
                                4000, "Description must be less than 4000 symbols"
                            ),
                        ]
                    ),
                ),
                ("created_at", models.DateField(blank=True, null=True)),
                ("media_type", models.CharField(editable=False, max_length=20)),
                ("created_by", models.CharField(editable=False, max_length=255)),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
            ],
            options={
                "ordering": ("first_name",),
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="UserMediaRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("review", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Finished"),
                            ("IP", "In progress"),
                            ("D", "Dropped"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_hidden", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "user_media_rating",
            },
        ),
        migrations.AlterModelOptions(
            name="mediauser",
            options={"ordering": ("username",)},
        ),
        migrations.AlterField(
            model_name="mediauser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.media",
                    ),
                ),
                ("chapters", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TB", "Traditional book"),
                            ("LN", "Light novel"),
                            ("WN", "Web novel"),
                            ("CS", "Comics"),
                            ("MA", "Manga"),
                            ("FF", "Fan fiction"),
                        ],
                        max_length=65,
                    ),
                ),
            ],
            bases=("media.media",),
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.media",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("duration", models.TimeField()),
            ],
            bases=("media.media",),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="media.media",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("F", "Finished"),
                            ("IP", "In progress"),
                            ("D", "Dropped"),
                        ],
                        max_length=255,
                    ),
                ),
                ("seasons", models.PositiveSmallIntegerField()),
                ("series_number", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OS", "Original series"),
                            ("SO", "Spin-off"),
                            ("AY", "Anthology"),
                            ("AD", "Adaptation"),
                            ("AE", "Anime"),
                        ],
                        max_length=65,
                    ),
                ),
            ],
            bases=("media.media",),
        ),
        migrations.AddField(
            model_name="media",
            name="creators",
            field=models.ManyToManyField(
                blank=True, related_name="media", to="media.creator"
            ),
        ),
        migrations.AddConstraint(
            model_name="creator",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "birth_date"), name="unique_creators"
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="genres",
            field=models.ManyToManyField(related_name="media", to="media.genre"),
        ),
        migrations.AddField(
            model_name="usermediarating",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_ratings",
                to="media.media",
            ),
        ),
        migrations.AddField(
            model_name="usermediarating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="users",
            field=models.ManyToManyField(
                related_name="media",
                through="media.UserMediaRating",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="usermediarating",
            constraint=models.UniqueConstraint(
                fields=("user", "media"), name="unique_reviews"
            ),
        ),
    ]
